[project]
name = "goodluckcat"
version = "0.1.0"
description = "好運貓貓"
dependencies = [
    "flask>=3.0.0",
]
requires-python = ">=3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"